# Generated by Django 4.2.28 on 2026-03-16 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivreurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville (Zone de livraison)')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, verbose_name='Type de véhicule (Ex: Moto, Camionnette)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
