# Generated by Django 4.2.28 on 2026-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_liv', models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaoundé')], max_length=50, verbose_name='Ville de livraison')),
                ('adr_prec', models.TextField(verbose_name='Adresse précise')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de livraison')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='LivreurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville (Zone de livraison)')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, verbose_name='Type de véhicule (Ex: Moto, Camionnette)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
        ),
    ]
