# Generated by Django 4.2.28 on 2026-03-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='ville_liv',
            field=models.CharField(max_length=100, verbose_name='Ville de livraison'),
        ),
    ]
