# Generated by Django 4.2.28 on 2026-03-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_ville_liv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='ville_liv',
            field=models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaoundé')], max_length=50, verbose_name='Ville de livraison'),
        ),
    ]
