# Generated by Django 4.2.28 on 2026-03-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant Total')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('expedie', 'Expédiée'), ('livre', 'Livrée'), ('annule', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('pay_mode', models.CharField(choices=[('nelsius', 'Nelsius'), ('fashi', 'Fashi'), ('cash', 'Cash')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('date_com', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_com'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix unitaire')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='catalog.product')),
            ],
        ),
    ]
