# Generated by Django 4.2.28 on 2026-03-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Code de confirmation'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison'),
        ),
    ]
