# Generated by Django 4.2.28 on 2026-03-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de Livraison'),
        ),
    ]
