# Generated by Django 4.2.28 on 2026-03-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_code_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='Signature du client (Base64)'),
        ),
    ]
