# Generated by Django 4.2.28 on 2026-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_mode',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('cash', 'Cash à la livraison'), ('nelsius', 'Nelsius'), ('fashi', 'Fashi')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
