# Generated by Django 4.2.28 on 2026-03-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='signature',
        ),
    ]
