# Generated by Django 4.2.28 on 2026-03-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_pay_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('expedie', 'En chemin'), ('livre', 'Livrée'), ('annule', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
