# Generated by Django 4.2.28 on 2026-03-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacité'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Couleur'),
        ),
    ]
