# Generated by Django 4.2.28 on 2026-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacité choisie'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur choisie'),
        ),
    ]
