# Generated by Django 4.2.28 on 2026-04-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options_and_more'),
        ('orders', '0006_orderitem_capacity_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='Variante'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('expedie', 'En chemin'), ('livre', 'Livrée'), ('retrait_valide', 'Retrait Validé'), ('annule', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
