# Generated by Django 4.2.28 on 2026-04-03 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_productvariant_stock_variantstock'),
        ('orders', '0007_orderitem_variant_alter_order_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.store', verbose_name='Boutique'),
        ),
    ]
