# Generated by Django 4.2.21 on 2026-05-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Payée'), ('expedie', 'En chemin'), ('livre', 'Livrée'), ('retrait_valide', 'Retrait Validé'), ('annule', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
