# Generated by Django 4.2.28 on 2026-03-27 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_pay_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_pay', models.CharField(choices=[('nelsius', 'Nelsius'), ('fashi', 'Fashi'), ('cash', 'Cash')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('ref_trans', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence de transaction')),
                ('mt_paye', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant payé')),
                ('date_pay', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('is_valide', models.BooleanField(default=False, verbose_name='Est valide')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_pay'],
            },
        ),
    ]
