# Generated by Django 4.2.28 on 2026-03-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse détaillée'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
