# Generated by Django 4.2.28 on 2026-04-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_adresse_customuser_ville_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_dispo',
            field=models.BooleanField(default=True, help_text='Indique si le livreur est prêt pour de nouvelles courses', verbose_name='Est disponible'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='solde_coll',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Portefeuille cash pour le livreur (montants encaissés)', max_digits=12, verbose_name='Solde collecté'),
        ),
    ]
