# Generated by Django 4.2.28 on 2026-03-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(default='', help_text='Nom de la catégorie', max_length=100, verbose_name='Nom')),
                ('slug_cat', models.SlugField(blank=True, help_text='Identifiant unique', unique=True)),
                ('desc_cat', models.TextField(blank=True, help_text='Description de la catégorie', verbose_name='Description')),
                ('img_cat', models.ImageField(blank=True, help_text='Image de la catégorie', null=True, upload_to='categories/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(default='', help_text='Nom complet de la variante', max_length=200, verbose_name='Nom du produit')),
                ('groupe_id', models.SlugField(help_text="Slug pour lier les variantes d'un même modèle produit", max_length=200)),
                ('prix_unit', models.DecimalField(decimal_places=0, help_text='Prix unitaire de cette variante', max_digits=12, verbose_name='Prix Unitaire (FCFA)')),
                ('couleur', models.CharField(blank=True, help_text='Couleur de la variante', max_length=50, null=True, verbose_name='Couleur')),
                ('capacite', models.CharField(blank=True, help_text='Capacité (ex: 128 Go)', max_length=50, null=True, verbose_name='Capacité')),
                ('stk_dla', models.PositiveIntegerField(default=0, help_text='Quantité en stock à Douala', verbose_name='Stock Douala')),
                ('stk_yde', models.PositiveIntegerField(default=0, help_text='Quantité en stock à Yaoundé', verbose_name='Stock Yaoundé')),
                ('specs', models.TextField(blank=True, help_text='Caractéristiques techniques (texte libre)', verbose_name='Spécifications')),
                ('img_path', models.ImageField(blank=True, help_text='Photo de la variante', null=True, upload_to='products/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_2ndmain', models.BooleanField(default=False, verbose_name='Seconde main')),
                ('fast_deal', models.BooleanField(default=False, verbose_name='Fast Deal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Produit (Variante)',
                'verbose_name_plural': 'Produits (Variantes)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du magasin')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
    ]
