# Generated by Django 4.2.28 on 2026-03-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_charfield_and_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
