# Generated by Django 4.2.28 on 2026-03-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Description complète du produit', verbose_name='Description'),
        ),
    ]
