# Generated by Django 4.2.28 on 2026-03-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_description'),
    ]

    operations = [
    ]
