# Generated by Django 4.2.28 on 2026-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productreview_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la couleur')),
                ('code', models.CharField(help_text='Code Hexa (ex: #000000)', max_length=7, verbose_name='Code Couleur')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.ManyToManyField(blank=True, to='catalog.color', verbose_name='couleurs disponible'),
        ),
    ]
