# Generated by Django 4.2.28 on 2026-03-26 20:15

from django.db import migrations


def create_default_stores(apps, schema_editor):
    Store = apps.get_model('catalog', 'Store')
    stores_data = [
        {
            'name': 'AUDSTOREsarl Douala',
            'city': 'douala',
            'address': 'Douala, Cameroun',
        },
        {
            'name': 'AUDSTOREsarl Yaoundé',
            'city': 'yaounde',
            'address': 'Rue Kennedy, ancien direction Orange, Yaoundé',
        },
    ]
    for data in stores_data:
        Store.objects.get_or_create(city=data['city'], defaults={
            'name': data['name'],
            'address': data['address'],
        })


def delete_default_stores(apps, schema_editor):
    Store = apps.get_model('catalog', 'Store')
    Store.objects.filter(city__in=['douala', 'yaounde']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_create_default_stores'),
    ]

    operations = [
        migrations.RunPython(create_default_stores, delete_default_stores),
    ]
