# Generated by Django 4.2.28 on 2026-03-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_color_alter_product_price_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Valeur (ex: 128 GB)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='color',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color',
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='catalog.color'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(help_text='Code Hexa (ex: #C0C0C0)', max_length=7),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom (ex: Titane)'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_capacities',
            field=models.ManyToManyField(blank=True, to='catalog.capacity'),
        ),
    ]
