# Generated by Django 4.2.28 on 2026-03-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_capacity_productvariant_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la caractéristique (ex: Écran, Batterie)')),
                ('value', models.CharField(max_length=255, verbose_name='Valeur (ex: 6.1 pouces, 3000 mAh)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Caractéristique Technique',
                'verbose_name_plural': 'Caractéristiques Techniques',
                'ordering': ['id'],
            },
        ),
    ]
