# Generated by Django 4.2.28 on 2026-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_create_default_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Valeur (ex: 128 Go)')),
            ],
            options={
                'verbose_name': 'Capacité',
                'verbose_name_plural': 'Capacités',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la couleur')),
                ('hex_code', models.CharField(default='#000000', max_length=7, verbose_name='Code Hexa')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='available_capacities',
            field=models.ManyToManyField(blank=True, to='catalog.capacity', verbose_name='Capacités disponibles'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='catalog.color', verbose_name='Couleurs disponibles'),
        ),
    ]
