# Generated by Django 4.2.28 on 2026-03-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_capacity_color_product_available_capacities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('slug_marque', models.SlugField(blank=True, unique=True)),
                ('img_marque', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Image de la marque')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom_marque'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_capacities',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.AlterField(
            model_name='product',
            name='capacite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.capacity', verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='couleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color', verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='product',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='Marque'),
        ),
    ]
