# Generated by Django 4.2.28 on 2026-03-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_brand_remove_product_available_capacities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacite',
            field=models.CharField(blank=True, choices=[('32Go', '32 Go'), ('64Go', '64 Go'), ('128Go', '128 Go'), ('256Go', '256 Go'), ('512Go', '512 Go'), ('1To', '1 To'), ('2To', '2 To'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='couleur',
            field=models.CharField(blank=True, choices=[('Noir', 'Noir'), ('Blanc', 'Blanc'), ('Gris', 'Gris'), ('Rouge', 'Rouge'), ('Bleu', 'Bleu'), ('Vert', 'Vert'), ('Jaune', 'Jaune'), ('Rose', 'Rose'), ('Or', 'Or'), ('Argent', 'Argent'), ('Bronze', 'Bronze'), ('Violet', 'Violet'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(blank=True, choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Tecno', 'Tecno'), ('Infinix', 'Infinix'), ('Itel', 'Itel'), ('Huawei', 'Huawei'), ('Nokia', 'Nokia'), ('Google', 'Google'), ('Sony', 'Sony'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Marque'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
