# Generated by Django 4.2.28 on 2026-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_capacite_alter_product_couleur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_capacities',
            field=models.CharField(blank=True, help_text='Séparez par des virgules (max 4)', max_length=255, verbose_name='Capacités disponibles'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, help_text='Séparez par des virgules (max 3)', max_length=255, verbose_name='Couleurs disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacite',
            field=models.CharField(blank=True, choices=[('32Go', '32 Go'), ('64Go', '64 Go'), ('128Go', '128 Go'), ('256Go', '256 Go'), ('512Go', '512 Go'), ('1To', '1 To'), ('2To', '2 To'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Capacité par défaut'),
        ),
        migrations.AlterField(
            model_name='product',
            name='couleur',
            field=models.CharField(blank=True, choices=[('Noir', 'Noir'), ('Blanc', 'Blanc'), ('Gris', 'Gris'), ('Rouge', 'Rouge'), ('Bleu', 'Bleu'), ('Vert', 'Vert'), ('Jaune', 'Jaune'), ('Rose', 'Rose'), ('Or', 'Or'), ('Argent', 'Argent'), ('Bronze', 'Bronze'), ('Violet', 'Violet'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Couleur par défaut'),
        ),
    ]
