# Generated by Django 4.2.28 on 2026-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_capacities',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Capacité (Go)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fast_deal',
            field=models.BooleanField(default=False, verbose_name='Fast Deal (offre rapide)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_second_hand',
            field=models.BooleanField(default=False, verbose_name='Seconde main'),
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
