# Generated by Django 4.2.28 on 2026-04-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_available_capacities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_capacities',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='capacite',
        ),
        migrations.RemoveField(
            model_name='product',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stk_dla',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stk_yde',
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='groupe_id',
            field=models.SlugField(blank=True, help_text='Slug unique du produit (auto-généré)', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom_prod',
            field=models.CharField(default='', max_length=200, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, verbose_name='Spécifications'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image Produit',
                'verbose_name_plural': 'Images Produit',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(blank=True, choices=[('Noir', 'Noir'), ('Blanc', 'Blanc'), ('Gris', 'Gris'), ('Rouge', 'Rouge'), ('Bleu', 'Bleu'), ('Vert', 'Vert'), ('Jaune', 'Jaune'), ('Rose', 'Rose'), ('Or', 'Or'), ('Argent', 'Argent'), ('Bronze', 'Bronze'), ('Violet', 'Violet'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Couleur')),
                ('capacite', models.CharField(blank=True, choices=[('32Go', '32 Go'), ('64Go', '64 Go'), ('128Go', '128 Go'), ('256Go', '256 Go'), ('512Go', '512 Go'), ('1To', '1 To'), ('2To', '2 To'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Capacité')),
                ('prix_unit', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (FCFA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Image variante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['capacite', 'couleur'],
                'unique_together': {('product', 'couleur', 'capacite')},
            },
        ),
    ]
