# Generated by Django 4.2.28 on 2026-03-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_available_capacities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Valeur (ex: 128 GB)')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom (ex: Titane)')),
                ('code', models.CharField(help_text='Code Hexa (ex: #C0C0C0)', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_capacities',
            field=models.ManyToManyField(blank=True, to='catalog.capacity'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='catalog.color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.capacity'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.color'),
        ),
    ]
