# Generated by Django 4.2.28 on 2026-04-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.CreateModel(
            name='VariantStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.store', verbose_name='Boutique')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Stock Boutique',
                'verbose_name_plural': 'Stocks Boutiques',
                'unique_together': {('variant', 'store')},
            },
        ),
    ]
