# Generated by Django 4.2.28 on 2026-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_productvariant_stock_variantstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='couleur',
            field=models.CharField(blank=True, choices=[('Noir', 'Noir'), ('Blanc', 'Blanc'), ('Gris', 'Gris'), ('Rouge', 'Rouge'), ('Bleu', 'Bleu'), ('Vert', 'Vert'), ('Jaune', 'Jaune'), ('Rose', 'Rose'), ('Or', 'Or'), ('Argent', 'Argent'), ('Bronze', 'Bronze'), ('Violet', 'Violet'), ('Titanium Naturel', 'Titanium Naturel'), ('Titanium Noir', 'Titanium Noir'), ('Titanium Blanc', 'Titanium Blanc'), ('Titanium Désert', 'Titanium Désert'), ('Lumière Stellaire', 'Lumière Stellaire'), ('Minuit', 'Minuit'), ('Mauve', 'Mauve'), ('Graphite', 'Graphite'), ('Bleu Pacifique', 'Bleu Pacifique'), ('Bleu Sierra', 'Bleu Sierra'), ('Vert Alpin', 'Vert Alpin'), ('Violet Intense', 'Violet Intense'), ('Autre', 'Autre')], max_length=50, null=True, verbose_name='Couleur'),
        ),
    ]
